# Generated by Django 6.0.5 on 2026-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplanner', '0002_depot_job_route_vehicle_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
