# Generated by Django 6.0.5 on 2026-06-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplanner', '0003_depot_is_active_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
